### ISSUE TITLE
"Too many open files" Error

### ISSUE THREAD

**Issue by rstemmer** [rstemmer/musicdb#11]
### Issue
"Too many open files" after a very long run time.

### Log

```
 LOG[2018-10-07 21:34:49|FATAL] server.py:Run.343: FATAL ERROR (shutting down server!!):
 LOG[2018-10-07 21:34:49|FATAL] server.py:Run.344: [Errno 24] Too many open files: '/data/musicdb/musicdb.fifo'
Traceback (most recent call last):
  File "/srv/musicdb/mdbapi/server.py", line 326, in Run
  File "/srv/musicdb/lib/namedpipe.py", line 93, in ReadLine
  File "/srv/musicdb/lib/namedpipe.py", line 91, in opener
OSError: [Errno 24] Too many open files: '/data/musicdb/musicdb.fifo'
```

**Comment by rstemmer** [comment]
Looks like a problem with the named pipe. 

```bash
lsof -p $( cat /data/musicdb/musicdb.pid)

# …
# python3 5484 musicdb  332r     FIFO               0,12      0t0 1033843325 pipe
# python3 5484 musicdb  333w     FIFO               0,12      0t0 1033843325 pipe
# python3 5484 musicdb  334u     unix 0x0000000012801911      0t0 1033870208 type=STREAM
# python3 5484 musicdb  335u     unix 0x00000000cf67d618      0t0 1033870209 type=STREAM
# …
```

The bus may be in [/lib/namedpipe.py; ReadLine; 63-106](https://github.com/rstemmer/musicdb/blob/master/lib/namedpipe.py#L63-L106)
This function is already hacked because Python had problems handling FIFO.

**Comment by rstemmer** [comment]
This issue becomes more and more annoying. FIFOs will be removed in Version 6.0.0.

**Comment by rstemmer** [comment]
**Observation:**
Whenever a new song gets loaded by the MusicDB Server two more file descriptors for FIFOs and Sockets appear in /proc/???/fd. (4 in total)

To reproduce:

- Wait until a song got played
- Press *Next* button.

Check via:
```
[M45ch1n3/pts/4:/proc/1637580] ll fd | grep pipe | wc -l && ll fd | grep socket | wc -l
```

The queue state makes MusicDB select a new random song.
Beside the FIFO implementation, now Randy, The MP3-Stream management and WebSocket implementation become candidate to be the reason for the "Too manny open files" Error.

**Comment by rstemmer** [comment]
**50% Done.**
The Unix-Pipe handlers come from the GStreamer interface. Destroying a `MP3Transcoder` object stopped GStreamer but did not close the Pipe handlers. So the source and sink pipe was left open which lead to two file handlers per song.

Next, the socket leak needs to be investigated.


The fact that the FIFO interface of MusicDB is not the reason for this bug does not change my opinion that there needs to be a better solution to trigger the MusicDB Server shutdown/cache-updates

**Comment by rstemmer** [comment]
**100% Done**

The last issue was strange. GStreamer did not close the file handler for the file to transcode.
Reading the documentation made the problem obvious. The pipeline needed to be dereferenced manually by calling unref().
This solved the issue with the additional handlers. (I've no idea why they were listed as sockets in /proc).
Anyway, now I had the problem that exiting the server lead to lots of "GLib-GObject-CRITICAL"-Errors.

These errors where produced in the PyFinalizex-function. After some tries I figured out that all unref-falls needed by GStreamer are done by Pythons garbage collector. This is what I originally assumed and why I never called unref.
For some reasons I cannot explain, the created GStreamerInterface object in MP3Transcoder got referenced until the Python finalizes. - ALL ever created GStreamerInterfaces! By setting the reference explicitly to `None` in the `__exit__` method of MP3Transcoder solved the problem for now.

I'm scared where else the garbage collector collects garbage instead of freeing the resources…

-> Issue closed.
