### ISSUE TITLE
AI broken. Importing tflearn failed

### ISSUE THREAD

**Issue by rstemmer** [rstemmer/musicdb#31]
```
[M45ch1n3/pts/4:/srv/musicdb] python
Python 3.8.1 (default, Dec 21 2019, 20:57:38) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflearn
2020-01-11 14:33:59.393571: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/tflearn/__init__.py", line 4, in <module>
    from . import config
  File "/usr/lib/python3.8/site-packages/tflearn/config.py", line 5, in <module>
    from .variables import variable
  File "/usr/lib/python3.8/site-packages/tflearn/variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
ModuleNotFoundError: No module named 'tensorflow.contrib'
>>> 
```

Installed tensorflow:

- python-tensorflow-cuda 2.1.0-1
- tensorflow-cuda 2.1.0-1
- tflearn (0.3.2)

The tflearn module was installed via pip 9.3 (python 3.8).

**Comment by rstemmer** [comment]
I need to replace tflearn.
It is old and does not support modern TensorFlow: [tensorflow issue 30794](https://github.com/tensorflow/tensorflow/issues/30794#issuecomment-512188521).

The broken AI becomes more and more a major issue. I now also have to extend the MusicDB command line module `musicai` to print a list of all albums that have not been analyzed yet.

**Comment by rstemmer** [comment]
In case this Issue got found via google:

The particular error ``from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope`` is [fixed in the TFLearn version on github](https://github.com/tflearn/tflearn/blob/master/tflearn/variables.py#L7).

But in general TFLearn is not ported to TensorFlow 2.x yet, and probably will never be (based on the overall activity of the TFLearn repository).

**Comment by rstemmer** [comment]
With the next version (5.3.0) MusicAI will be marked as deprecated and will be removed in future versions.
The effort to fix this is too time consuming.
