### ISSUE TITLE
musicdb add: Crash and missleading UI

### ISSUE THREAD

**Issue by rstemmer** [rstemmer/musicdb#35]
The *add* module of MusicDB marks invalid song names.
I thought it will automatically clean those names. Of cause it does nothing as long as the user does not explicitly gives the command to do something (in this case pressing *c* to give the command to clean the names).
Even worse is the fact, that MusicDB crashes when forgetting to press *c*:
```
Traceback (most recent call last):
  File "/srv/musicdb/musicdb", line 208, in <module>
    exitcode = modobj.MDBM_Main(args)
  File "/srv/musicdb/mod/add.py", line 824, in MDBM_Main
    self.RunImportProcess(data)
  File "/srv/musicdb/mod/add.py", line 756, in RunImportProcess
    self.AddAlbum(newalbumpath, artist["id"])
  File "/srv/musicdb/mdbapi/database.py", line 531, in AddAlbum
    raise AssertionError("Analysing path \"%s\" failed!", songpaths[0])
AssertionError: ('Analysing path "%s" failed!', 'Die Kreatur/2020 - Panoptikum/Die Kreatur - Panoptikum - 01 DIE KREATUR.mp3')
```

**Problem 1:** Make sure the user is aware that the song-name-remarks are indicating problems with the naming, and *not* an applied solution.
**Problem 2:** If the user leaves those problems unsolved, a message box should appear allowing the user to solve the issues, or cancel the import process.
**Problem 3:** The exception listed above should not be unhandled!

**Comment by rstemmer** [comment]
The whole TextUI needs to be refactored. Its complexity is out of control. But for now all issues were fixed in Version 5.3.0
