### ISSUE TITLE
Server event-loop broken with Python 3.7 / Autobahn 18.8.1

### ISSUE THREAD

**Issue by rstemmer** [rstemmer/musicdb#9]
The implementation of handling the Autobahn event loop broke with the update to Python 3.7 / Autobahn 18.8.1.

Pure asyncio event loop
```
 LOG[2018-08-25 09:03:42|DEBUG] websocket.py:__init__.40: Using WebSocket module AutobahnPython/18.8.1
 LOG[2018-08-25 09:03:42|INFO ] server.py: MusicDB WebSocket Server (TLSv1.2 secured) listening to port 9001
 LOG[2018-08-25 09:03:42|INFO ] server.py: Setup complete. Executing server.
 LOG[2018-08-25 09:03:42|FATAL] server.py:Run.343: FATAL ERROR (shutting down server!!):
 LOG[2018-08-25 09:03:42|FATAL] server.py:Run.344: cannot reuse already awaited coroutine
Traceback (most recent call last):
  File "/srv/musicdb/mdbapi/server.py", line 324, in Run
    tlswsserver.HandleEvents()
  File "/srv/musicdb/lib/ws/server.py", line 175, in HandleEvents
    self.eventloop.run_until_complete(self.coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
RuntimeError: cannot reuse already awaited coroutine
```

With uvloop as event loop
```
 LOG[2018-08-21 18:13:24|DEBUG] websocket.py:__init__.40: Using WebSocket module AutobahnPython/18.8.1
 LOG[2018-08-21 18:13:24|INFO ] server.py: MusicDB WebSocket Server (TLSv1.2 secured) listening to port 9001
 LOG[2018-08-21 18:13:24|INFO ] server.py: Setup complete. Executing server.
 LOG[2018-08-21 18:13:24|FATAL] server.py:Run.344: FATAL ERROR (shutting down server!!):
 LOG[2018-08-21 18:13:24|FATAL] server.py:Run.345: cannot reuse already awaited coroutine
Traceback (most recent call last):
  File "/srv/musicdb/mdbapi/server.py", line 325, in Run
    tlswsserver.HandleEvents()
  File "/srv/musicdb/lib/ws/server.py", line 181, in HandleEvents
    self.eventloop.run_until_complete(self.coro)
  File "uvloop/loop.pyx", line 1448, in uvloop.loop.Loop.run_until_complete
RuntimeError: cannot reuse already awaited coroutine
```

**Comment by rstemmer** [comment]
**Hotfix** to be able to run the MusicDB Websocket Server:

Replace [line 171 in lib/ws/server.py](https://github.com/rstemmer/musicdb/blob/master/lib/ws/server.py#L171).

Before:
```
def HandleEvents(self):
    self.eventloop.run_until_complete(self.coro)
```

After:
```
def HandleEvents(self):
    self.eventloop.run_forever()
```

**This change will break other less important features:**
* The FIFO interface for shutting down the server or updating its caches won't work anymore
* You cannot shutdown the server in a clean way! - Use Ctrl-C to interrupt the server, then remove _musicdb.pid_ and _musicdb.fifo_ from the MusicDB data directory.

**Comment by rstemmer** [comment]
Bug fixed.
It was an issue with the asyncio module. `run_until_complete` needs to get a task as argument, no longer a coroutine.
